// Forel - A native macOS file-automation app
// Copyright (C) 2026  Lab421
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

/// Noise generated by the OS or other apps, never something a rule should
/// see: Finder's folder metadata cache, AppleDouble resource forks (common
/// on network/exFAT volumes), Microsoft Office's lock files for an open
/// document, and browser download placeholders that are still being written.
/// Shared by the watcher and the Dry Run/Run Now folder scan so all three
/// execution paths agree on what's visible.
enum SystemFileFilter {
    private static let incompleteDownloadSuffixes = [
        ".crdownload", // Chrome, Edge, Brave, and other Chromium browsers
        ".download", // Safari
        ".part", // Firefox and several download managers
        ".opdownload", // Opera
        ".aria2", // aria2 sidecar while a transfer is in progress
    ]

    private static let incompleteDownloadPrefixes = [
        ".com.google.Chrome.",
        ".com.microsoft.edgemac.",
        ".com.brave.Browser.",
        ".com.vivaldi.Vivaldi.",
        ".com.operasoftware.Opera.",
        ".org.chromium.Chromium.",
    ]

    static func isExcluded(_ filename: String) -> Bool {
        let lowercased = filename.lowercased()
        return filename == ".DS_Store"
            || filename.hasPrefix("._")
            || filename.hasPrefix("~$")
            || incompleteDownloadPrefixes.contains { filename.hasPrefix($0) }
            || incompleteDownloadSuffixes.contains { lowercased.hasSuffix($0) }
    }
}
