// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the service bound to the frontend. Each exported method becomes an
 * IPC-callable function in the generated TypeScript bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as rules$0 from "./internal/rules/models.js";

/**
 * AddCustomTag persists a user-defined tag so it appears across sessions.
 */
export function AddCustomTag(name: string): $CancellablePromise<void> {
    return $Call.ByID(2266566637, name);
}

export function AddWatchedFolder(path: string): $CancellablePromise<rules$0.WatchedFolder> {
    return $Call.ByID(1819455854, path).then(($result: any) => {
        return $$createType0($result);
    });
}

export function CreateRule(folderID: string, name: string): $CancellablePromise<rules$0.Rule> {
    return $Call.ByID(487083315, folderID, name).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeleteRule(ruleID: string): $CancellablePromise<void> {
    return $Call.ByID(4007199332, ruleID);
}

/**
 * GetMacosTags returns text tags: Finder favourites + custom tags from the DB.
 * The 7 system colour names are excluded — colours are handled separately.
 */
export function GetMacosTags(): $CancellablePromise<string[]> {
    return $Call.ByID(61451397).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetRules(folderID: string): $CancellablePromise<rules$0.Rule[]> {
    return $Call.ByID(2351437958, folderID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetWatchedFolders(): $CancellablePromise<rules$0.WatchedFolder[]> {
    return $Call.ByID(862549760).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * PreviewRules simulates rule evaluation over the folder without running actions.
 */
export function PreviewRules(folderID: string): $CancellablePromise<rules$0.PreviewResult> {
    return $Call.ByID(423622998, folderID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function RemoveWatchedFolder(id: string): $CancellablePromise<void> {
    return $Call.ByID(175233033, id);
}

/**
 * RunRulesNow evaluates and applies all rules to every file in the folder.
 */
export function RunRulesNow(folderID: string): $CancellablePromise<string[]> {
    return $Call.ByID(2301641879, folderID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SelectDirectory opens a native folder picker and returns the chosen path, or
 * "" if the user cancelled.
 */
export function SelectDirectory(): $CancellablePromise<string> {
    return $Call.ByID(1735672136);
}

export function ToggleRule(ruleID: string, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3680875275, ruleID, enabled);
}

export function ToggleWatchedFolder(id: string, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(542622897, id, enabled);
}

export function UpdateRule(rule: rules$0.Rule): $CancellablePromise<void> {
    return $Call.ByID(480709666, rule);
}

// Private type creation functions
const $$createType0 = rules$0.WatchedFolder.createFrom;
const $$createType1 = rules$0.Rule.createFrom;
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Array($$createType1);
const $$createType4 = $Create.Array($$createType0);
const $$createType5 = rules$0.PreviewResult.createFrom;
