// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Action is one operation performed when a rule matches. Params is a freeform
 * JSON object whose keys depend on Kind (see action.go).
 */
export class Action {
    "id": string;
    "rule_id": string;
    "kind": ActionKind;
    "params": { [_ in string]?: any };
    "position": number;

    /** Creates a new Action instance. */
    constructor($$source: Partial<Action> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("rule_id" in $$source)) {
            this["rule_id"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = ActionKind.$zero;
        }
        if (!("params" in $$source)) {
            this["params"] = {};
        }
        if (!("position" in $$source)) {
            this["position"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Action instance from a string or object.
     */
    static createFrom($$source: any = {}): Action {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("params" in $$parsedSource) {
            $$parsedSource["params"] = $$createField3_0($$parsedSource["params"]);
        }
        return new Action($$parsedSource as Partial<Action>);
    }
}

/**
 * ActionKind enumerates the supported actions. String values mirror the
 * snake_case stored in SQLite and consumed by the frontend.
 */
export enum ActionKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ActMoveToFolder = "move_to_folder",
    ActCopyToFolder = "copy_to_folder",
    ActRename = "rename",
    ActMoveToTrash = "move_to_trash",
    ActDelete = "delete",
    ActAddTag = "add_tag",
    ActRemoveTag = "remove_tag",
    ActSetColorLabel = "set_color_label",
    ActRunScript = "run_script",
};

/**
 * Condition is a single predicate evaluated against a file.
 */
export class Condition {
    "id": string;
    "rule_id": string;
    "kind": ConditionKind;
    "operator": Operator;
    "value": string;

    /** Creates a new Condition instance. */
    constructor($$source: Partial<Condition> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("rule_id" in $$source)) {
            this["rule_id"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = ConditionKind.$zero;
        }
        if (!("operator" in $$source)) {
            this["operator"] = Operator.$zero;
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Condition instance from a string or object.
     */
    static createFrom($$source: any = {}): Condition {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Condition($$parsedSource as Partial<Condition>);
    }
}

/**
 * ConditionKind enumerates the supported condition types. The string values
 * mirror the snake_case stored in SQLite and consumed by the frontend.
 */
export enum ConditionKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CondName = "name",
    CondExtension = "extension",
    CondKind = "kind",
    CondSizeBytes = "size_bytes",
    CondTags = "tags",
    CondColorLabel = "color_label",
    CondContents = "contents",
};

/**
 * ConditionMatch decides whether all or any conditions must hold for a rule.
 */
export enum ConditionMatch {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MatchAll = "all",
    MatchAny = "any",
};

/**
 * FilePreview groups the rules that match a single file.
 */
export class FilePreview {
    "path": string;
    "name": string;
    "rules": RulePreview[];

    /** Creates a new FilePreview instance. */
    constructor($$source: Partial<FilePreview> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("rules" in $$source)) {
            this["rules"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FilePreview instance from a string or object.
     */
    static createFrom($$source: any = {}): FilePreview {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rules" in $$parsedSource) {
            $$parsedSource["rules"] = $$createField2_0($$parsedSource["rules"]);
        }
        return new FilePreview($$parsedSource as Partial<FilePreview>);
    }
}

/**
 * Operator enumerates comparison operators usable by conditions.
 */
export enum Operator {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    OpIs = "is",
    OpIsNot = "is_not",
    OpContains = "contains",
    OpDoesNotContain = "does_not_contain",
    OpStartsWith = "starts_with",
    OpEndsWith = "ends_with",
    OpMatchesRegex = "matches_regex",
    OpGreaterThan = "greater_than",
    OpLessThan = "less_than",
};

/**
 * PreviewResult is the outcome of a dry-run over a folder.
 */
export class PreviewResult {
    "files_scanned": number;
    "matches": FilePreview[];

    /** Creates a new PreviewResult instance. */
    constructor($$source: Partial<PreviewResult> = {}) {
        if (!("files_scanned" in $$source)) {
            this["files_scanned"] = 0;
        }
        if (!("matches" in $$source)) {
            this["matches"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PreviewResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PreviewResult {
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("matches" in $$parsedSource) {
            $$parsedSource["matches"] = $$createField1_0($$parsedSource["matches"]);
        }
        return new PreviewResult($$parsedSource as Partial<PreviewResult>);
    }
}

/**
 * Rule groups conditions and actions for a watched folder.
 */
export class Rule {
    "id": string;
    "folder_id": string;
    "name": string;
    "enabled": boolean;
    "condition_match": ConditionMatch;
    "conditions": Condition[];
    "actions": Action[];
    "priority": number;
    "created_at": string;

    /** Creates a new Rule instance. */
    constructor($$source: Partial<Rule> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("folder_id" in $$source)) {
            this["folder_id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("condition_match" in $$source)) {
            this["condition_match"] = ConditionMatch.$zero;
        }
        if (!("conditions" in $$source)) {
            this["conditions"] = [];
        }
        if (!("actions" in $$source)) {
            this["actions"] = [];
        }
        if (!("priority" in $$source)) {
            this["priority"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Rule instance from a string or object.
     */
    static createFrom($$source: any = {}): Rule {
        const $$createField5_0 = $$createType6;
        const $$createField6_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("conditions" in $$parsedSource) {
            $$parsedSource["conditions"] = $$createField5_0($$parsedSource["conditions"]);
        }
        if ("actions" in $$parsedSource) {
            $$parsedSource["actions"] = $$createField6_0($$parsedSource["actions"]);
        }
        return new Rule($$parsedSource as Partial<Rule>);
    }
}

/**
 * RulePreview describes the actions a matching rule would perform.
 */
export class RulePreview {
    "rule_id": string;
    "rule_name": string;
    "actions": string[];

    /** Creates a new RulePreview instance. */
    constructor($$source: Partial<RulePreview> = {}) {
        if (!("rule_id" in $$source)) {
            this["rule_id"] = "";
        }
        if (!("rule_name" in $$source)) {
            this["rule_name"] = "";
        }
        if (!("actions" in $$source)) {
            this["actions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RulePreview instance from a string or object.
     */
    static createFrom($$source: any = {}): RulePreview {
        const $$createField2_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("actions" in $$parsedSource) {
            $$parsedSource["actions"] = $$createField2_0($$parsedSource["actions"]);
        }
        return new RulePreview($$parsedSource as Partial<RulePreview>);
    }
}

/**
 * WatchedFolder is a directory Forel monitors for rule evaluation.
 */
export class WatchedFolder {
    "id": string;
    "path": string;
    "enabled": boolean;
    "created_at": string;

    /** Creates a new WatchedFolder instance. */
    constructor($$source: Partial<WatchedFolder> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WatchedFolder instance from a string or object.
     */
    static createFrom($$source: any = {}): WatchedFolder {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WatchedFolder($$parsedSource as Partial<WatchedFolder>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = RulePreview.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = FilePreview.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = Condition.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = Action.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Array($Create.Any);
